name: proc-workflow
on: [push]
jobs: 
   test:
     runs-n: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-go@v1
         with:
             go-version: '1.15'
       - run: go test ./...